"""Single-file TOBE RAG flow for block parsing and rule-first guidance.

This module intentionally keeps the TOBE-stage RAG logic small:
1. Split source SQL into a main block plus nested subquery blocks.
2. Mask literals and normalize each block into a comparable shape.
3. Compare each block against `tobe_rule_catalog.json` example_bad_sql values.
4. Build a deterministic rewrite plan and reassembly checklist.

The final TOBE SQL is still generated by the existing TOBE prompt, but the
prompt now receives only this focused block-level RAG context.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
import json
import re

from app.features.tobe.tobe_rule_vector_service import tobe_rule_vector_service


_STRING_LITERAL_RE = re.compile(r"'(?:''|[^'])*'")
_NUMBER_LITERAL_RE = re.compile(r"\b\d+(?:\.\d+)?\b")
_COLUMN_REF_RE = re.compile(r"\b([A-Z_][A-Z0-9_$#]*)\.([A-Z_][A-Z0-9_$#]*)\b")
_FROM_ALIAS_RE = re.compile(
    r"(?i)(\bFROM\b|\bJOIN\b|,)\s*(SUBQUERY_\d+|[A-Z_][A-Z0-9_$#.]*)(?:\s+(?:AS\s+)?([A-Z_][A-Z0-9_$#]*))?"
)
_WHITESPACE_RE = re.compile(r"\s+")
_FROM_SECTION_RE = re.compile(r"(?is)\bFROM\b(?P<body>.*?)(?=\bWHERE\b|\bGROUP\s+BY\b|\bORDER\s+BY\b|\bHAVING\b|$)")
@dataclass
class BlockRuleMatch:
    rule_id: str
    score: float
    guidance: list[str] = field(default_factory=list)
    example_bad_sql: str = ""
    example_tuned_sql: str = ""


@dataclass
class SqlBlock:
    block_id: str
    role: str
    parent_block_id: str | None
    raw_sql: str
    masked_sql: str
    canonical_sql: str
    top_rule_matches: list[BlockRuleMatch] = field(default_factory=list)


@dataclass
class TobeBlockRagResult:
    flow_kind: str
    source_sql: str
    blocks: list[SqlBlock] = field(default_factory=list)
    rewrite_steps: list[str] = field(default_factory=list)
    validation_checks: list[str] = field(default_factory=list)


def build_tobe_block_rag_context(source_sql: str) -> str:
    """Return compact JSON prompt context for the TOBE block RAG flow."""
    result = analyze_tobe_block_rag(source_sql)
    payload = {
        "flow_kind": result.flow_kind,
        "source_sql": result.source_sql,
        "blocks": [asdict(block) for block in result.blocks],
        "rewrite_steps": result.rewrite_steps,
        "validation_checks": result.validation_checks,
    }
    return json.dumps(payload, ensure_ascii=False, indent=2)


def analyze_tobe_block_rag(source_sql: str) -> TobeBlockRagResult:
    """Analyze one FROM_SQL with the simplified block-based TOBE RAG flow."""
    normalized_source = _normalize_spacing(source_sql)
    blocks = _extract_blocks(normalized_source)
    for block in blocks:
        block.top_rule_matches = _match_rules_for_block(block)
    return TobeBlockRagResult(
        flow_kind="BLOCK_RULE_VECTOR_ONLY",
        source_sql=normalized_source,
        blocks=blocks,
        rewrite_steps=_build_rewrite_steps(blocks),
        validation_checks=_build_validation_checks(),
    )


def _extract_blocks(source_sql: str) -> list[SqlBlock]:
    counter = {"value": 1}
    flattened: list[SqlBlock] = []

    def _walk(sql_text: str, block_id: str, role: str, parent_block_id: str | None) -> str:
        sql_text = sql_text.strip().rstrip(";")
        chunks: list[str] = []
        cursor = 0
        index = 0
        while index < len(sql_text):
            if sql_text[index] != "(":
                index += 1
                continue
            end = _find_matching_paren(sql_text, index)
            if end < 0:
                break
            inner = sql_text[index + 1 : end].strip()
            if not re.match(r"(?is)^select\b", inner):
                index += 1
                continue
            subquery_id = f"SUBQUERY_{counter['value']}"
            counter["value"] += 1
            chunks.append(sql_text[cursor:index])
            chunks.append(f"({subquery_id})")
            _walk(inner, subquery_id, "SUBQUERY", block_id)
            cursor = end + 1
            index = end + 1
        chunks.append(sql_text[cursor:])
        masked_sql = _normalize_spacing("".join(chunks))
        flattened.append(
            SqlBlock(
                block_id=block_id,
                role=role,
                parent_block_id=parent_block_id,
                raw_sql=sql_text,
                masked_sql=masked_sql,
                canonical_sql=_canonicalize_sql(masked_sql),
            )
        )
        return masked_sql

    _walk(source_sql, "MAIN", "MAIN_SQL", None)
    flattened.sort(key=lambda item: (item.block_id != "MAIN", item.block_id))
    return flattened


def _find_matching_paren(sql_text: str, start_index: int) -> int:
    depth = 0
    in_string = False
    index = start_index
    while index < len(sql_text):
        char = sql_text[index]
        if char == "'" and (index + 1 >= len(sql_text) or sql_text[index + 1] != "'"):
            in_string = not in_string
        elif not in_string:
            if char == "(":
                depth += 1
            elif char == ")":
                depth -= 1
                if depth == 0:
                    return index
        elif char == "'" and index + 1 < len(sql_text) and sql_text[index + 1] == "'":
            index += 1
        index += 1
    return -1


def _canonicalize_sql(sql_text: str) -> str:
    masked_sql = _mask_literals(sql_text.upper())
    masked_sql = re.sub(r"\(\s*(SUBQUERY_\d+)\s*\)", r" \1 ", masked_sql)

    table_map: dict[str, str] = {}
    alias_map: dict[str, str] = {}
    column_map: dict[str, str] = {}
    from_section_match = _FROM_SECTION_RE.search(masked_sql)
    from_section = from_section_match.group("body") if from_section_match else ""

    def _table_name(token: str) -> str:
        value = token.strip().upper()
        if value not in table_map:
            table_map[value] = f"T{len(table_map) + 1}"
        return table_map[value]

    for match in _FROM_ALIAS_RE.finditer(f"FROM {from_section}"):
        table_token = match.group(2).strip().upper()
        alias_token = (match.group(3) or "").strip().upper()
        if table_token.startswith("SUBQUERY_"):
            if alias_token and alias_token not in alias_map:
                alias_map[alias_token] = f"A{len(alias_map) + 1}"
            continue
        _table_name(table_token)
        if alias_token and alias_token not in alias_map:
            alias_map[alias_token] = f"A{len(alias_map) + 1}"

    def _column_name(token: str) -> str:
        value = token.strip().upper()
        if value not in column_map:
            column_map[value] = f"C{len(column_map) + 1}"
        return column_map[value]

    def _replace_from_alias(match: re.Match[str]) -> str:
        prefix = match.group(1)
        table_token = match.group(2).strip().upper()
        alias_token = (match.group(3) or "").strip().upper()
        if table_token.startswith("SUBQUERY_"):
            mapped_table = table_token
        else:
            mapped_table = table_map.get(table_token, table_token)
        if alias_token:
            mapped_alias = alias_map.get(alias_token, alias_token)
            return f"{prefix} {mapped_table} {mapped_alias}"
        return f"{prefix} {mapped_table}"

    canonical = masked_sql
    if from_section_match:
        replaced_from = _FROM_ALIAS_RE.sub(_replace_from_alias, f"FROM {from_section}")
        canonical = (
            masked_sql[: from_section_match.start()]
            + replaced_from
            + masked_sql[from_section_match.end() :]
        )

    def _replace_column(match: re.Match[str]) -> str:
        left = match.group(1).upper()
        right = match.group(2).upper()
        mapped_left = alias_map.get(left) or table_map.get(left) or left
        return f"{mapped_left}.{_column_name(right)}"

    canonical = _COLUMN_REF_RE.sub(_replace_column, canonical)
    canonical = _normalize_spacing(canonical)
    return canonical


def _mask_literals(sql_text: str) -> str:
    string_counter = {"value": 1}
    number_counter = {"value": 1}

    def _replace_string(_match: re.Match[str]) -> str:
        token = f"STR_{string_counter['value']}"
        string_counter["value"] += 1
        return token

    def _replace_number(_match: re.Match[str]) -> str:
        token = f"NUM_{number_counter['value']}"
        number_counter["value"] += 1
        return token

    masked = _STRING_LITERAL_RE.sub(_replace_string, sql_text)
    masked = _NUMBER_LITERAL_RE.sub(_replace_number, masked)
    return masked


def _normalize_spacing(sql_text: str) -> str:
    return _WHITESPACE_RE.sub(" ", (sql_text or "").strip())
def _rule_specific_boost(block: SqlBlock, rule_id: str) -> float:
    upper = block.masked_sql.upper()
    boost = 0.0
    if rule_id == "RULE_VM001":
        if block.block_id == "MAIN" and "FROM" in upper and "SUBQUERY_" in upper:
            boost += 0.35
        if block.block_id.startswith("SUBQUERY_") and _is_simple_inline_view_block(block):
            boost += 0.55
    if rule_id in {"RULE_VM004", "RULE_F005"} and re.search(r"\bIN\s*\(\s*SUBQUERY_\d+\s*\)", upper):
        boost += 0.40
    if rule_id == "RULE_VM004" and block.block_id.startswith("SUBQUERY_"):
        if _is_single_key_subquery_block(block):
            boost += 0.75
    return boost


def _match_rules_for_block(block: SqlBlock) -> list[BlockRuleMatch]:
    query_text = json.dumps(
        {
            "block_id": block.block_id,
            "role": block.role,
            "raw_sql": block.raw_sql,
            "masked_sql": block.masked_sql,
            "canonical_sql": block.canonical_sql,
        },
        ensure_ascii=False,
        sort_keys=True,
    )
    retrieved = tobe_rule_vector_service.retrieve_similar_rules(query_text=query_text, top_k=6)
    scored: list[BlockRuleMatch] = []
    for rule, similarity in retrieved:
        normalized_similarity = max(0.0, min((similarity + 1.0) / 2.0, 1.0))
        score = normalized_similarity + _rule_specific_boost(block, rule.rule_id)
        if score <= 0.05:
            continue
        scored.append(
            BlockRuleMatch(
                rule_id=rule.rule_id,
                score=round(min(score, 1.0), 4),
                guidance=list(rule.guidance),
                example_bad_sql=rule.example_bad_sql,
                example_tuned_sql=rule.example_tuned_sql,
            )
        )
    scored.sort(key=lambda item: item.score, reverse=True)
    return scored[:3]


def _build_rewrite_steps(blocks: list[SqlBlock]) -> list[str]:
    block_map = {block.block_id: block for block in blocks}
    main_block = block_map.get("MAIN")
    steps: list[str] = []
    if not main_block:
        return steps

    child_blocks = [block for block in blocks if block.parent_block_id == "MAIN"]
    for child in child_blocks:
        top_rule_ids = {match.rule_id for match in child.top_rule_matches}
        if "RULE_VM001" in top_rule_ids or _is_simple_inline_view_block(child):
            steps.append(
                f"{child.block_id} is an inline-view merge candidate. Expand its base tables back into MAIN and replace projected alias references with base table columns."
            )

    for child in child_blocks:
        if re.search(rf"\bIN\s*\(\s*{child.block_id}\s*\)", main_block.masked_sql.upper()):
            top_rule_ids = {match.rule_id for match in main_block.top_rule_matches + child.top_rule_matches}
            if "RULE_VM004" in top_rule_ids or "RULE_F005" in top_rule_ids or _is_single_key_subquery_block(child):
                steps.append(
                    f"{child.block_id} is an IN-subquery unnest candidate. Convert `IN ({child.block_id})` into an equivalent join predicate in MAIN."
                )

    if steps:
        steps.append(
            "After block-level rewrites, merge duplicate base-table access when the same table is joined through equivalent key predicates."
        )
    else:
        steps.append("No strong block rewrite signal was found. Keep the original block structure and rely on mapping rules only.")
    return steps


def _is_simple_inline_view_block(block: SqlBlock) -> bool:
    upper = block.masked_sql.upper()
    if not block.block_id.startswith("SUBQUERY_"):
        return False
    if any(token in upper for token in (" DISTINCT ", " GROUP BY ", " HAVING ", " UNION ", " FETCH FIRST ", " ROWNUM ")):
        return False
    from_match = _FROM_SECTION_RE.search(upper)
    if not from_match:
        return False
    from_body = from_match.group("body")
    return "," in from_body or " JOIN " in from_body


def _is_single_key_subquery_block(block: SqlBlock) -> bool:
    upper = block.masked_sql.upper()
    if not block.block_id.startswith("SUBQUERY_"):
        return False
    select_match = re.search(r"(?is)\bSELECT\b(.*?)\bFROM\b", upper)
    if not select_match:
        return False
    projection = select_match.group(1)
    columns = [item.strip() for item in projection.split(",") if item.strip()]
    return len(columns) == 1


def _build_validation_checks() -> list[str]:
    return [
        "Each subquery block rewrite must preserve the selected columns and parent join/filter semantics.",
        "After reassembly, every SUBQUERY_n placeholder must be removed from the final SQL.",
        "Do not keep duplicate base tables if the same table can absorb the filter after unnesting or view merging.",
        "Final SQL must still satisfy mapping rules and the original row-grain intent.",
    ]
