-- =============================================================
-- hr_complex_mapping_rules_table.sql
-- Oracle 19c compatible mapping metadata (6 rules)
-- Columns: FROM_TABLE, FROM_COL, TO_TABLE, TO_COL
-- =============================================================

-- -----------------------------------------------------------------
-- RULE 01 : COMPLEX_JOIN -> HR_EMP_DEPT_JOB_SNAP
-- -----------------------------------------------------------------
SELECT 'HR.EMPLOYEES e LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID' AS FROM_TABLE, 'EMPLOYEE_ID' AS FROM_COL, 'HR_EMP_DEPT_JOB_SNAP' AS TO_TABLE, 'EMPLOYEE_ID' AS TO_COL FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID', 'FIRST_NAME', 'HR_EMP_DEPT_JOB_SNAP', 'FIRST_NAME' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID', 'LAST_NAME', 'HR_EMP_DEPT_JOB_SNAP', 'LAST_NAME' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID', 'EMAIL', 'HR_EMP_DEPT_JOB_SNAP', 'EMAIL' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID', 'PHONE_NUMBER', 'HR_EMP_DEPT_JOB_SNAP', 'PHONE_NUMBER' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID', 'HIRE_DATE', 'HR_EMP_DEPT_JOB_SNAP', 'HIRE_DATE' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID', 'DEPARTMENT_ID', 'HR_EMP_DEPT_JOB_SNAP', 'DEPARTMENT_ID' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID', 'DEPARTMENT_NAME', 'HR_EMP_DEPT_JOB_SNAP', 'DEPARTMENT_NAME' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID', 'JOB_ID', 'HR_EMP_DEPT_JOB_SNAP', 'JOB_ID' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID', 'JOB_TITLE', 'HR_EMP_DEPT_JOB_SNAP', 'JOB_TITLE' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID', 'CURRENT_SALARY', 'HR_EMP_DEPT_JOB_SNAP', 'CURRENT_SALARY' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID', 'COMMISSION_PCT', 'HR_EMP_DEPT_JOB_SNAP', 'COMMISSION_PCT' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID', 'MANAGER_ID', 'HR_EMP_DEPT_JOB_SNAP', 'MANAGER_ID' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID', 'DEPT_MANAGER_ID', 'HR_EMP_DEPT_JOB_SNAP', 'DEPT_MANAGER_ID' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID', 'SALARY_BAND', 'HR_EMP_DEPT_JOB_SNAP', 'SALARY_BAND' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID', 'JOB_RANGE_STATUS', 'HR_EMP_DEPT_JOB_SNAP', 'JOB_RANGE_STATUS' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID', 'MANAGER_EXISTS_YN', 'HR_EMP_DEPT_JOB_SNAP', 'MANAGER_EXISTS_YN' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID', 'DEPT_SALARY_RANK', 'HR_EMP_DEPT_JOB_SNAP', 'DEPT_SALARY_RANK' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID', 'JOB_SALARY_RANK', 'HR_EMP_DEPT_JOB_SNAP', 'JOB_SALARY_RANK' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID', 'DEPT_EMP_COUNT', 'HR_EMP_DEPT_JOB_SNAP', 'DEPT_EMP_COUNT' FROM DUAL
;

-- -----------------------------------------------------------------
-- RULE 02 : COMPLEX_JOIN -> HR_DEPT_PAYROLL_ROLLUP_F
-- -----------------------------------------------------------------
SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID' AS FROM_TABLE, 'DEPARTMENT_ID' AS FROM_COL, 'HR_DEPT_PAYROLL_ROLLUP_F' AS TO_TABLE, 'DEPARTMENT_ID' AS TO_COL FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'DEPARTMENT_NAME', 'HR_DEPT_PAYROLL_ROLLUP_F', 'DEPARTMENT_NAME' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'DEPT_MANAGER_ID', 'HR_DEPT_PAYROLL_ROLLUP_F', 'DEPT_MANAGER_ID' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'EMP_COUNT', 'HR_DEPT_PAYROLL_ROLLUP_F', 'EMP_COUNT' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'DISTINCT_JOB_COUNT', 'HR_DEPT_PAYROLL_ROLLUP_F', 'DISTINCT_JOB_COUNT' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'TOTAL_SALARY', 'HR_DEPT_PAYROLL_ROLLUP_F', 'TOTAL_SALARY' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'AVG_SALARY', 'HR_DEPT_PAYROLL_ROLLUP_F', 'AVG_SALARY' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'MIN_SALARY', 'HR_DEPT_PAYROLL_ROLLUP_F', 'MIN_SALARY' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'MAX_SALARY', 'HR_DEPT_PAYROLL_ROLLUP_F', 'MAX_SALARY' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'MEDIAN_SALARY', 'HR_DEPT_PAYROLL_ROLLUP_F', 'MEDIAN_SALARY' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'SALARY_STDDEV', 'HR_DEPT_PAYROLL_ROLLUP_F', 'SALARY_STDDEV' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'FIRST_HIRE_DATE', 'HR_DEPT_PAYROLL_ROLLUP_F', 'FIRST_HIRE_DATE' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'LAST_HIRE_DATE', 'HR_DEPT_PAYROLL_ROLLUP_F', 'LAST_HIRE_DATE' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'HIGH_SALARY_COUNT', 'HR_DEPT_PAYROLL_ROLLUP_F', 'HIGH_SALARY_COUNT' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'LOW_SALARY_COUNT', 'HR_DEPT_PAYROLL_ROLLUP_F', 'LOW_SALARY_COUNT' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'DEPT_SIZE_BAND', 'HR_DEPT_PAYROLL_ROLLUP_F', 'DEPT_SIZE_BAND' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'DEPT_PAY_BAND', 'HR_DEPT_PAYROLL_ROLLUP_F', 'DEPT_PAY_BAND' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'JOB_DIVERSITY_BAND', 'HR_DEPT_PAYROLL_ROLLUP_F', 'JOB_DIVERSITY_BAND' FROM DUAL
;

-- -----------------------------------------------------------------
-- RULE 03 : COMPLEX_RESHAPE -> HR_EMP_CAREER_EVENT_F
-- -----------------------------------------------------------------
SELECT '(CURRENT UNION ALL HISTORY) FROM HR.EMPLOYEES, HR.JOB_HISTORY' AS FROM_TABLE, 'EMPLOYEE_ID' AS FROM_COL, 'HR_EMP_CAREER_EVENT_F' AS TO_TABLE, 'EMPLOYEE_ID' AS TO_COL FROM DUAL
UNION ALL SELECT '(CURRENT UNION ALL HISTORY) FROM HR.EMPLOYEES, HR.JOB_HISTORY', 'EVENT_SOURCE', 'HR_EMP_CAREER_EVENT_F', 'EVENT_SOURCE' FROM DUAL
UNION ALL SELECT '(CURRENT UNION ALL HISTORY) FROM HR.EMPLOYEES, HR.JOB_HISTORY', 'EVENT_DATE', 'HR_EMP_CAREER_EVENT_F', 'EVENT_DATE' FROM DUAL
UNION ALL SELECT '(CURRENT UNION ALL HISTORY) FROM HR.EMPLOYEES, HR.JOB_HISTORY', 'EVENT_END_DATE', 'HR_EMP_CAREER_EVENT_F', 'EVENT_END_DATE' FROM DUAL
UNION ALL SELECT '(CURRENT UNION ALL HISTORY) FROM HR.EMPLOYEES, HR.JOB_HISTORY', 'JOB_ID', 'HR_EMP_CAREER_EVENT_F', 'JOB_ID' FROM DUAL
UNION ALL SELECT '(CURRENT UNION ALL HISTORY) FROM HR.EMPLOYEES, HR.JOB_HISTORY', 'DEPARTMENT_ID', 'HR_EMP_CAREER_EVENT_F', 'DEPARTMENT_ID' FROM DUAL
UNION ALL SELECT '(CURRENT UNION ALL HISTORY) FROM HR.EMPLOYEES, HR.JOB_HISTORY', 'CURRENT_SALARY', 'HR_EMP_CAREER_EVENT_F', 'CURRENT_SALARY' FROM DUAL
UNION ALL SELECT '(CURRENT UNION ALL HISTORY) FROM HR.EMPLOYEES, HR.JOB_HISTORY', 'HISTORY_GAP_DAYS', 'HR_EMP_CAREER_EVENT_F', 'HISTORY_GAP_DAYS' FROM DUAL
UNION ALL SELECT '(CURRENT UNION ALL HISTORY) FROM HR.EMPLOYEES, HR.JOB_HISTORY', 'EVENT_TYPE', 'HR_EMP_CAREER_EVENT_F', 'EVENT_TYPE' FROM DUAL
UNION ALL SELECT '(CURRENT UNION ALL HISTORY) FROM HR.EMPLOYEES, HR.JOB_HISTORY', 'EVENT_STATUS', 'HR_EMP_CAREER_EVENT_F', 'EVENT_STATUS' FROM DUAL
UNION ALL SELECT '(CURRENT UNION ALL HISTORY) FROM HR.EMPLOYEES, HR.JOB_HISTORY', 'EMP_EVENT_SEQ', 'HR_EMP_CAREER_EVENT_F', 'EMP_EVENT_SEQ' FROM DUAL
UNION ALL SELECT '(CURRENT UNION ALL HISTORY) FROM HR.EMPLOYEES, HR.JOB_HISTORY', 'PREV_JOB_ID', 'HR_EMP_CAREER_EVENT_F', 'PREV_JOB_ID' FROM DUAL
UNION ALL SELECT '(CURRENT UNION ALL HISTORY) FROM HR.EMPLOYEES, HR.JOB_HISTORY', 'PREV_DEPARTMENT_ID', 'HR_EMP_CAREER_EVENT_F', 'PREV_DEPARTMENT_ID' FROM DUAL
;

-- -----------------------------------------------------------------
-- RULE 04 : COMPLEX_RESHAPE -> HR_EMP_HISTORY_STACKED_F
-- -----------------------------------------------------------------
SELECT '(AA/BB/CC/EE CASE UNION ALL) FROM HR.EMPLOYEES, HR.JOB_HISTORY' AS FROM_TABLE, 'EMPLOYEE_ID' AS FROM_COL, 'HR_EMP_HISTORY_STACKED_F' AS TO_TABLE, 'EMPLOYEE_ID' AS TO_COL FROM DUAL
UNION ALL SELECT '(AA/BB/CC/EE CASE UNION ALL) FROM HR.EMPLOYEES, HR.JOB_HISTORY', 'EVENT_DATE', 'HR_EMP_HISTORY_STACKED_F', 'EVENT_DATE' FROM DUAL
UNION ALL SELECT '(AA/BB/CC/EE CASE UNION ALL) FROM HR.EMPLOYEES, HR.JOB_HISTORY', 'EVENT_END_DATE', 'HR_EMP_HISTORY_STACKED_F', 'EVENT_END_DATE' FROM DUAL
UNION ALL SELECT '(AA/BB/CC/EE CASE UNION ALL) FROM HR.EMPLOYEES, HR.JOB_HISTORY', 'DD', 'HR_EMP_HISTORY_STACKED_F', 'DD' FROM DUAL
UNION ALL SELECT '(AA/BB/CC/EE CASE UNION ALL) FROM HR.EMPLOYEES, HR.JOB_HISTORY', 'EE_SIGNAL', 'HR_EMP_HISTORY_STACKED_F', 'EE_SIGNAL' FROM DUAL
UNION ALL SELECT '(AA/BB/CC/EE CASE UNION ALL) FROM HR.EMPLOYEES, HR.JOB_HISTORY', 'SOURCE_TAG', 'HR_EMP_HISTORY_STACKED_F', 'SOURCE_TAG' FROM DUAL
UNION ALL SELECT '(AA/BB/CC/EE CASE UNION ALL) FROM HR.EMPLOYEES, HR.JOB_HISTORY', 'CURRENT_SALARY', 'HR_EMP_HISTORY_STACKED_F', 'CURRENT_SALARY' FROM DUAL
UNION ALL SELECT '(AA/BB/CC/EE CASE UNION ALL) FROM HR.EMPLOYEES, HR.JOB_HISTORY', 'HISTORY_GAP_DAYS', 'HR_EMP_HISTORY_STACKED_F', 'HISTORY_GAP_DAYS' FROM DUAL
UNION ALL SELECT '(AA/BB/CC/EE CASE UNION ALL) FROM HR.EMPLOYEES, HR.JOB_HISTORY', 'JOB_ID', 'HR_EMP_HISTORY_STACKED_F', 'JOB_ID' FROM DUAL
UNION ALL SELECT '(AA/BB/CC/EE CASE UNION ALL) FROM HR.EMPLOYEES, HR.JOB_HISTORY', 'DEPARTMENT_ID', 'HR_EMP_HISTORY_STACKED_F', 'DEPARTMENT_ID' FROM DUAL
UNION ALL SELECT '(AA/BB/CC/EE CASE UNION ALL) FROM HR.EMPLOYEES, HR.JOB_HISTORY', 'TRACK_TYPE', 'HR_EMP_HISTORY_STACKED_F', 'TRACK_TYPE' FROM DUAL
UNION ALL SELECT '(AA/BB/CC/EE CASE UNION ALL) FROM HR.EMPLOYEES, HR.JOB_HISTORY', 'TRACK_SEQ', 'HR_EMP_HISTORY_STACKED_F', 'TRACK_SEQ' FROM DUAL
;

-- -----------------------------------------------------------------
-- RULE 05 : COMPLEX_TYPE_CAST -> HR_EMP_TYPECAST_AUDIT
-- -----------------------------------------------------------------
SELECT 'HR.EMPLOYEES e LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID' AS FROM_TABLE, 'EMPLOYEE_ID_TXT' AS FROM_COL, 'HR_EMP_TYPECAST_AUDIT' AS TO_TABLE, 'EMPLOYEE_ID_TXT' AS TO_COL FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID', 'HIRE_DATE_YYYYMMDD', 'HR_EMP_TYPECAST_AUDIT', 'HIRE_DATE_YYYYMMDD' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID', 'SALARY_TXT', 'HR_EMP_TYPECAST_AUDIT', 'SALARY_TXT' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID', 'SALARY_NUM', 'HR_EMP_TYPECAST_AUDIT', 'SALARY_NUM' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID', 'COMMISSION_TXT', 'HR_EMP_TYPECAST_AUDIT', 'COMMISSION_TXT' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID', 'DEPARTMENT_ID_TXT', 'HR_EMP_TYPECAST_AUDIT', 'DEPARTMENT_ID_TXT' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID', 'JOB_ID_TXT', 'HR_EMP_TYPECAST_AUDIT', 'JOB_ID_TXT' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID', 'MIN_SALARY_TXT', 'HR_EMP_TYPECAST_AUDIT', 'MIN_SALARY_TXT' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID', 'MAX_SALARY_TXT', 'HR_EMP_TYPECAST_AUDIT', 'MAX_SALARY_TXT' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID', 'MIN_SALARY_DECIMAL', 'HR_EMP_TYPECAST_AUDIT', 'MIN_SALARY_DECIMAL' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID', 'MAX_SALARY_DECIMAL', 'HR_EMP_TYPECAST_AUDIT', 'MAX_SALARY_DECIMAL' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID', 'HIRE_DATE_ROUNDTRIP', 'HR_EMP_TYPECAST_AUDIT', 'HIRE_DATE_ROUNDTRIP' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID', 'EMP_HASH_KEY', 'HR_EMP_TYPECAST_AUDIT', 'EMP_HASH_KEY' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID', 'CAST_QUALITY_STATUS', 'HR_EMP_TYPECAST_AUDIT', 'CAST_QUALITY_STATUS' FROM DUAL
UNION ALL SELECT 'HR.EMPLOYEES e LEFT JOIN HR.JOBS j ON j.JOB_ID=e.JOB_ID LEFT JOIN HR.DEPARTMENTS d ON d.DEPARTMENT_ID=e.DEPARTMENT_ID', 'JOB_RANGE_CHECK', 'HR_EMP_TYPECAST_AUDIT', 'JOB_RANGE_CHECK' FROM DUAL
;

-- -----------------------------------------------------------------
-- RULE 06 : COMPLEX_TYPE_CAST -> HR_DEPT_TYPECAST_AUDIT
-- -----------------------------------------------------------------
SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID' AS FROM_TABLE, 'DEPARTMENT_ID_TXT' AS FROM_COL, 'HR_DEPT_TYPECAST_AUDIT' AS TO_TABLE, 'DEPARTMENT_ID_TXT' AS TO_COL FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'DEPARTMENT_ID_LPAD', 'HR_DEPT_TYPECAST_AUDIT', 'DEPARTMENT_ID_LPAD' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'DEPARTMENT_NAME', 'HR_DEPT_TYPECAST_AUDIT', 'DEPARTMENT_NAME' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'EMP_COUNT_TXT', 'HR_DEPT_TYPECAST_AUDIT', 'EMP_COUNT_TXT' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'EMP_COUNT_NUM', 'HR_DEPT_TYPECAST_AUDIT', 'EMP_COUNT_NUM' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'TOTAL_SALARY_TXT', 'HR_DEPT_TYPECAST_AUDIT', 'TOTAL_SALARY_TXT' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'AVG_SALARY_TXT', 'HR_DEPT_TYPECAST_AUDIT', 'AVG_SALARY_TXT' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'MIN_SALARY_TXT', 'HR_DEPT_TYPECAST_AUDIT', 'MIN_SALARY_TXT' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'MAX_SALARY_TXT', 'HR_DEPT_TYPECAST_AUDIT', 'MAX_SALARY_TXT' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'AVG_SALARY_NUM', 'HR_DEPT_TYPECAST_AUDIT', 'AVG_SALARY_NUM' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'SNAP_DATE_YYYYMMDD', 'HR_DEPT_TYPECAST_AUDIT', 'SNAP_DATE_YYYYMMDD' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'SNAP_DATE', 'HR_DEPT_TYPECAST_AUDIT', 'SNAP_DATE' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'DEPT_HASH_KEY', 'HR_DEPT_TYPECAST_AUDIT', 'DEPT_HASH_KEY' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'DEPT_SIZE_BAND', 'HR_DEPT_TYPECAST_AUDIT', 'DEPT_SIZE_BAND' FROM DUAL
UNION ALL SELECT 'HR.DEPARTMENTS d LEFT JOIN HR.EMPLOYEES e ON e.DEPARTMENT_ID=d.DEPARTMENT_ID', 'DEPT_PAY_BAND', 'HR_DEPT_TYPECAST_AUDIT', 'DEPT_PAY_BAND' FROM DUAL
;


